// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoj-8sbj0n-8BuzT0IzLfQ2yEGioAQ3m0',
    appId: '1:47698965041:android:e2e407dc19f3cde6e55b10',
    messagingSenderId: '47698965041',
    projectId: 'xpresion-2db29',
    databaseURL: 'https://xpresion-2db29.firebaseio.com',
    storageBucket: 'xpresion-2db29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt90UF7okLpWrjoOKp8Tni99lOoifDXJc',
    appId: '1:47698965041:ios:af499f533cfa43cfe55b10',
    messagingSenderId: '47698965041',
    projectId: 'xpresion-2db29',
    databaseURL: 'https://xpresion-2db29.firebaseio.com',
    storageBucket: 'xpresion-2db29.appspot.com',
    androidClientId:
        '47698965041-8l7ldteatfaqu2iki14kuvnte5me2dkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.xprapp',
  );
}
